id: PA8ABFAA0
initial_creation_type: input
source_metadata:
  Title: Dhih Journal Vol.33
  Editor: Samten, Ngawang & Janardan Pandey
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2002'
  Sitātapatrā dhāraṇī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:57:18.432668'
last_modified_at: '2022-03-08T15:57:18.432677'
